import 'package:sqflite/sqflite.dart';
import 'package:sqflite_common_ffi_web/sqflite_ffi_web.dart';

// Web has no native SQLite, so sqflite needs a WASM-backed factory instead
// (sqlite3.wasm running in a Web Worker, persisted via IndexedDB/OPFS). The
// worker + wasm assets are generated by a real Flutter toolchain
// (`dart run sqflite_common_ffi_web:setup`, run in CI — see
// .github/workflows/build-web.yml) and are not checked into this repo.
void configureDatabaseFactory() {
  databaseFactory = databaseFactoryFfiWeb;
}
